/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.akhir;

import java.awt.Component;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import proyek.akhir.model.JenisTarif;
import proyek.akhir.model.Pelanggan;
import proyek.akhir.model.Pembayaran;

/**
 *
 * @author alhamdi
 */
public class DataPembayaran extends javax.swing.JFrame {
    
    DefaultTableModel tabelModel;
    Support<Pembayaran> support;
    

    public JLabel getNama_petugas() {
        return nama_petugas;
    }

    public void setNama_petugas(JLabel nama_petugas) {
        this.nama_petugas = nama_petugas;
    }
    
    public DataPembayaran() {
        initComponents();
        nama_petugas.setVisible(false);
        String[] column = {"No", "No Pembayaran", "Kode Pelanggan", "Nama Petugas", "Tanggal Pembayaran", "Denda", "Total", "Actions"};
        support = new Support<Pembayaran>(tabelModel, tablePembayaran, Pembayaran.pembayaran, column);
        tampilData();
        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        dml.addElement("-- Pilih Kode Pelanggan --");
        for(int i= 0; i<Pelanggan.pelanggan.size(); i++){
            dml.addElement(Pelanggan.pelanggan.get(i).getKodePelanggan());
        }
        kode_pelanggan.setModel(dml);
    }
    
    public void tampilData(){
        Object[][] objData = new Object[support.list.size()][support.column.length];
        int no = 0;
        for(Pembayaran n : Pembayaran.pembayaran){
            Object[] data = {no+1, n.getNoPembayaran(), n.getKodePelanggan(), n.getNama_petugas(), n.getTanggalBayar(), n.getDenda(), n.getTotal(), "Cetak Struk"};
            objData[no] = data;
            no++;
        }
        support.tampilData(objData);
        tablePembayaran.getColumnModel().getColumn(7).setCellRenderer(new ButtonRenderer());
        tablePembayaran.getColumnModel().getColumn(7).setCellEditor(new ButtonEditor(new JTextField()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kode_pelanggan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        daya = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        no_pembayaran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tanggal_pembayaran = new com.toedter.calendar.JCalendar();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        no_handphone = new javax.swing.JLabel();
        golongan = new javax.swing.JLabel();
        tarif = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();
        denda = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        konsumsi_daya = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        tanggal_lahir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btn_simpan6 = new javax.swing.JButton();
        btn_update6 = new javax.swing.JButton();
        btn_delete6 = new javax.swing.JButton();
        nama_petugas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePembayaran = new javax.swing.JTable();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Pembayaran"));
        jPanel5.setToolTipText("Form");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setText("No Pembayaran");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel3.setText("Kode Pelanggan");

        kode_pelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kode_pelanggan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                kode_pelangganPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                kode_pelangganPopupMenuWillBecomeVisible(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel4.setText("Tanggal Pembayaran");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel5.setText("Daya yang di hasilkan watt/bulan");

        jButton1.setText("Lihat Detail Pembayaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_pembayaran)
                    .addComponent(daya)
                    .addComponent(kode_pelanggan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tanggal_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(264, 264, 264))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kode_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Pemabayaran"));
        jPanel6.setToolTipText("Form");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("DATA PELANGGAN");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel8.setText("Nama Pelanggan");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel9.setText("Jenis Kelamin");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel10.setText("Alamat");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel11.setText("Nomor Handphone");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel12.setText("Total");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel13.setText("Golongan");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel14.setText("Tarif");

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel15.setText("Keterangan");

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel16.setText("DATA GOLONGAN TARIF");

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel17.setText("Denda");

        nama_pelanggan.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        nama_pelanggan.setText("-");

        jenis_kelamin.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jenis_kelamin.setText("-");

        alamat.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        alamat.setText("-");

        no_handphone.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        no_handphone.setText("-");

        golongan.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        golongan.setText("-");

        tarif.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        tarif.setText("-");

        keterangan.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        keterangan.setText("-");

        denda.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        denda.setText("0");

        total.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        total.setText("0");

        konsumsi_daya.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        konsumsi_daya.setText("0");

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel19.setText("Tarif Konsumsi Daya");

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel18.setText("Tanggal Lahir");

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel20.setText("Agama");

        agama.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        agama.setText("-");

        tanggal_lahir.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        tanggal_lahir.setText("-");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agama)
                    .addComponent(keterangan)
                    .addComponent(jLabel16)
                    .addComponent(nama_pelanggan)
                    .addComponent(jLabel7)
                    .addComponent(jenis_kelamin)
                    .addComponent(alamat)
                    .addComponent(no_handphone)
                    .addComponent(golongan)
                    .addComponent(tarif)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(denda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(konsumsi_daya, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(tanggal_lahir))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nama_pelanggan))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jenis_kelamin))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(alamat))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(no_handphone))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tanggal_lahir))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(agama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(golongan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarif)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(keterangan))
                .addGap(53, 53, 53)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konsumsi_daya)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denda)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(total))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMBAYARAN");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));
        jPanel11.setToolTipText("Form");

        btn_simpan6.setText("Simpan");
        btn_simpan6.setEnabled(false);
        btn_simpan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan6ActionPerformed(evt);
            }
        });

        btn_update6.setText("Update");
        btn_update6.setEnabled(false);
        btn_update6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update6ActionPerformed(evt);
            }
        });

        btn_delete6.setText("Delete");
        btn_delete6.setEnabled(false);
        btn_delete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete6ActionPerformed(evt);
            }
        });

        nama_petugas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        nama_petugas.setText("DATA PELANGGAN");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_simpan6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete6)
                .addGap(29, 29, 29)
                .addComponent(nama_petugas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan6)
                    .addComponent(btn_update6)
                    .addComponent(btn_delete6)
                    .addComponent(nama_petugas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "No Pembayaran", "Kode Pelanggan", "Nama Petugas", "Tanggal Pembayaran", "Denda", "Total", "Actions"
            }
        ));
        tablePembayaran.setRowHeight(25);
        tablePembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePembayaran);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan6ActionPerformed
        Pembayaran e = new Pembayaran(
            no_pembayaran.getText(),
            String.valueOf(tanggal_pembayaran.getDayChooser().getDay()) + "-" + String.valueOf(tanggal_pembayaran.getMonthChooser().getMonth() + 1) + "-" + String.valueOf(tanggal_pembayaran.getYearChooser().getYear()),
            Integer.parseInt(daya.getText()),
            Double.parseDouble(denda.getText().split(",")[1]),
            Double.parseDouble(total.getText().split(",")[1]),
            nama_petugas.getText(),
            kode_pelanggan.getSelectedItem().toString(),
            nama_pelanggan.getText(),
            jenis_kelamin.getText(),
            tanggal_lahir.getText(),
            alamat.getText(),
            agama.getText(),
            no_handphone.getText(),
            golongan.getText(),
            Double.parseDouble(tarif.getText()),
            keterangan.getText(),
            new JButton("Actions"));
        support.insertData(e);
        clearForm();
        tampilData();
        JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan!");
    }//GEN-LAST:event_btn_simpan6ActionPerformed

    private void clearForm(){
        no_pembayaran.setText("");
        Calendar today = Calendar.getInstance();
        tanggal_pembayaran.setCalendar(today);
        daya.setText("");
        denda.setText("Rp, 0");
        total.setText("Rp, 0");
        kode_pelanggan.setSelectedItem("-- Pilih Kode Pelanggan --");
        nama_pelanggan.setText("");
        jenis_kelamin.setText("");
        tanggal_lahir.setText("");
        alamat.setText("");
        agama.setText("");
        no_handphone.setText("");
        golongan.setText("");
        tarif.setText("");
        keterangan.setText("");
        konsumsi_daya.setText("Rp, 0");
        btn_simpan6.setEnabled(false);
        btn_update6.setEnabled(false);
        btn_delete6.setEnabled(false);
        no_pembayaran.setEnabled(true);
    }
    
    private byte CariKode(String data){
        byte urutan = -1;
        for(byte i=0;  i < this.support.getList().size(); i++){
            if(this.support.getList().get(i).getNoPembayaran().equals(data)){
                    urutan = i;
                    break;
            }
        }
        return urutan;
    }
    
    private void btn_update6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update6ActionPerformed
        byte urutan = this.CariKode(no_pembayaran.getText());
        Pembayaran e = new Pembayaran(
            no_pembayaran.getText(),
            String.valueOf(tanggal_pembayaran.getDayChooser().getDay()) + "-" + String.valueOf(tanggal_pembayaran.getMonthChooser().getMonth() + 1) + "-" + String.valueOf(tanggal_pembayaran.getYearChooser().getYear()),
            Integer.parseInt(daya.getText()),
            Double.parseDouble(denda.getText().split(",")[1]),
            Double.parseDouble(total.getText().split(",")[1]),
            nama_petugas.getText(),
            kode_pelanggan.getSelectedItem().toString(),
            nama_pelanggan.getText(),
            jenis_kelamin.getText(),
            tanggal_lahir.getText(),
            alamat.getText(),
            agama.getText(),
            no_handphone.getText(),
            golongan.getText(),
            Double.parseDouble(tarif.getText()),
            keterangan.getText(),
            new JButton("Actions"));
        this.support.updateData(urutan, e);
        clearForm();
        tampilData();
        JOptionPane.showMessageDialog(null, "Data Berhasil Di Update!");
    }//GEN-LAST:event_btn_update6ActionPerformed

    private void btn_delete6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete6ActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus Data Ini ?",
            "Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (opsi == JOptionPane.YES_OPTION){
            this.support.deleteData(this.CariKode(no_pembayaran.getText()));
            clearForm();
            tampilData();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus!");
        }
    }//GEN-LAST:event_btn_delete6ActionPerformed

    private void kode_pelangganPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_kode_pelangganPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_kode_pelangganPopupMenuWillBecomeInvisible

    private void kode_pelangganPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_kode_pelangganPopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_pelangganPopupMenuWillBecomeVisible

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tmp = (String)kode_pelanggan.getSelectedItem();
        for(int i= 0; i<Pelanggan.pelanggan.size(); i++){
            if(Pelanggan.pelanggan.get(i).getKodePelanggan().equals(tmp)){
                nama_pelanggan.setText(Pelanggan.pelanggan.get(i).getNama());
                jenis_kelamin.setText(Pelanggan.pelanggan.get(i).getJk());
                alamat.setText(Pelanggan.pelanggan.get(i).getAlamat());
                no_handphone.setText(Pelanggan.pelanggan.get(i).getNohp());
                golongan.setText(Pelanggan.pelanggan.get(i).getGolongan());
                tarif.setText(String.valueOf(Pelanggan.pelanggan.get(i).getTarif()));
                keterangan.setText(Pelanggan.pelanggan.get(i).getKeterangan());
                tanggal_lahir.setText(Pelanggan.pelanggan.get(i).getTgl_lahir());
                agama.setText(Pelanggan.pelanggan.get(i).getAgama());
            }
        }
        konsumsi_daya.setText("Rp, " + String.valueOf(Double.parseDouble(tarif.getText()) * (Double.parseDouble(daya.getText()) / 1000 )));
        denda.setText("Rp, " + String.valueOf(Pembayaran.HitungDenda(String.valueOf(tanggal_pembayaran.getDayChooser().getDay()), golongan.getText())));
        total.setText("Rp, " + String.valueOf(Double.parseDouble(tarif.getText()) * (Double.parseDouble(daya.getText()) / 1000 ) + Pembayaran.HitungDenda(String.valueOf(tanggal_pembayaran.getDayChooser().getDay()), golongan.getText()) ));
        byte urutan = this.CariKode(no_pembayaran.getText());
        if(urutan == -1){
            btn_simpan6.setEnabled(true);
            btn_update6.setEnabled(false);
            btn_delete6.setEnabled(false);
        }else{
            btn_simpan6.setEnabled(false);
            btn_update6.setEnabled(true);
            btn_delete6.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablePembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePembayaranMouseClicked
        no_pembayaran.setText(support.getItemInTable(1));
        kode_pelanggan.setSelectedItem(support.getItemInTable(2));
        tanggal_pembayaran.getDayChooser().setDay(Integer.parseInt(support.getDay(support.getItemInTable(4))));
        tanggal_pembayaran.getMonthChooser().setMonth(Integer.parseInt(support.getMonth(support.getItemInTable(4))) - 1);
        tanggal_pembayaran.getYearChooser().setYear(Integer.parseInt(support.getYear(support.getItemInTable(4))));
        denda.setText(support.getItemInTable(5));
        total.setText(support.getItemInTable(6));
        byte urutan = this.CariKode(support.getItemInTable(1));
        alamat.setText(support.getList().get(urutan).getAlamat());
        jenis_kelamin.setText(support.getList().get(urutan).getJk());
        no_handphone.setText(support.getList().get(urutan).getNohp());
        tanggal_lahir.setText(support.getList().get(urutan).getTgl_lahir());
        agama.setText(support.getList().get(urutan).getAgama());
        golongan.setText(support.getList().get(urutan).getGolongan());
        tarif.setText(String.valueOf(support.getList().get(urutan).getTarif()));
        keterangan.setText(support.getList().get(urutan).getKeterangan());
        daya.setText(String.valueOf(support.getList().get(urutan).getDaya()));
        konsumsi_daya.setText("Rp, " + String.valueOf(Double.parseDouble(tarif.getText()) * (Double.parseDouble(daya.getText()) / 1000 )));
        btn_update6.setEnabled(true);
        btn_delete6.setEnabled(true);
        btn_simpan6.setEnabled(false);
        no_pembayaran.setEnabled(false);
    }//GEN-LAST:event_tablePembayaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btn_delete2;
    private javax.swing.JButton btn_delete3;
    private javax.swing.JButton btn_delete4;
    private javax.swing.JButton btn_delete6;
    private javax.swing.JButton btn_new2;
    private javax.swing.JButton btn_new3;
    private javax.swing.JButton btn_new4;
    private javax.swing.JButton btn_simpan2;
    private javax.swing.JButton btn_simpan3;
    private javax.swing.JButton btn_simpan4;
    private javax.swing.JButton btn_simpan6;
    private javax.swing.JButton btn_update2;
    private javax.swing.JButton btn_update3;
    private javax.swing.JButton btn_update4;
    private javax.swing.JButton btn_update6;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.JTextField daya;
    private javax.swing.JLabel denda;
    private javax.swing.JLabel golongan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenis_kelamin;
    private javax.swing.JLabel keterangan;
    private javax.swing.JComboBox<String> kode_pelanggan;
    private javax.swing.JLabel konsumsi_daya;
    private javax.swing.JLabel nama_pelanggan;
    private javax.swing.JLabel nama_petugas;
    private javax.swing.JLabel no_handphone;
    private javax.swing.JTextField no_pembayaran;
    private javax.swing.JTable tablePembayaran;
    private javax.swing.JLabel tanggal_lahir;
    private com.toedter.calendar.JCalendar tanggal_pembayaran;
    private javax.swing.JLabel tarif;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
