/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.akhir;

import proyek.akhir.model.JenisTarif;
import proyek.akhir.model.Pelanggan;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alhamdi
 */
public class DataPelanggan extends javax.swing.JFrame {

    DefaultTableModel tabelModel;
    Support<Pelanggan> support;
    JenisTarif js;
    
    /**
     * Creates new form DataPelanggan
     */
    public DataPelanggan() {
        initComponents();
        String[] column = {"No", "Kode Pelanggan", "Nama", "Jenis Kelamin", "Tanggal Lahir", "Alamat", "Agama", "No Handphone", "Golongan", "Tarif", "Keterangan"};
        support = new Support<Pelanggan>(tabelModel, tablePelanggan, Pelanggan.pelanggan, column);
        tampilData();
        if(JenisTarif.jenis_tarif.size() == 0){
            js = new JenisTarif();
        }
        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        dml.addElement("-- Pilih Jenis Tarif --");
        for(int i= 0; i<JenisTarif.jenis_tarif.size(); i++){
            dml.addElement(JenisTarif.jenis_tarif.get(i).getGolongan());
        }
        jenis_tarif.setModel(dml);
    }
    
    public void tampilData(){
        Object[][] objData = new Object[support.list.size()][support.column.length];
        int no = 0;
        for(Pelanggan n : Pelanggan.pelanggan){
            String[] data = {String.valueOf(no+1), n.getKodePelanggan(), n.getNama(), n.getJk(), n.getTgl_lahir(), n.getAlamat(), n.getAgama(), n.getNohp(), n.getGolongan(), String.valueOf(n.getTarif()), n.getKeterangan()};
            objData[no] = data;
            no++;
        }
        support.tampilData(objData);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateComponentFormatter1 = new org.jdatepicker.impl.DateComponentFormatter();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kode_pelanggan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tanggal_lahir = new com.toedter.calendar.JCalendar();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        agama = new javax.swing.JComboBox<>();
        alamat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        no_hp = new javax.swing.JTextField();
        jenis_kelamin = new javax.swing.JComboBox<>();
        nama_lengkap = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_new2 = new javax.swing.JButton();
        btn_simpan2 = new javax.swing.JButton();
        btn_update2 = new javax.swing.JButton();
        btn_delete2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cari_data = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jenis_tarif = new javax.swing.JComboBox<>();
        tarif = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        keterangan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENDAFTARAN PELANGGAN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulir"));
        jPanel1.setToolTipText("Form");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setText("Kode Pelanggan");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel5.setText("Nama Lengkap");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel7.setText("Jenis Kelamin");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel8.setText("Tanggal Lahir");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel9.setText("Agama");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel10.setText("No Handphone");

        agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Konghucu" }));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel11.setText("Alamat");

        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamat)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agama, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(kode_pelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(no_hp)
                            .addComponent(jenis_kelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(tanggal_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(nama_lengkap)))
                    .addComponent(jLabel11))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_lengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggal_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));
        jPanel4.setToolTipText("Form");

        btn_new2.setText("New");
        btn_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_new2ActionPerformed(evt);
            }
        });

        btn_simpan2.setText("Simpan");
        btn_simpan2.setEnabled(false);
        btn_simpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan2ActionPerformed(evt);
            }
        });

        btn_update2.setText("Update");
        btn_update2.setEnabled(false);
        btn_update2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update2ActionPerformed(evt);
            }
        });

        btn_delete2.setText("Delete");
        btn_delete2.setEnabled(false);
        btn_delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_new2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_update2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_simpan2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new2)
                    .addComponent(btn_simpan2)
                    .addComponent(btn_update2)
                    .addComponent(btn_delete2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel12.setText("Cari Data");

        cari_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_dataKeyPressed(evt);
            }
        });

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePelanggan);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarif"));
        jPanel5.setToolTipText("Form");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel13.setText("Pilih Tarif");

        jenis_tarif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        jenis_tarif.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jenis_tarifPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        tarif.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel14.setText("Tarif");

        keterangan.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel15.setText("Keterangan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jenis_tarif, 0, 388, Short.MAX_VALUE)
                    .addComponent(tarif)
                    .addComponent(keterangan)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenis_tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(8, 8, 8)
                .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari_data)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_new2ActionPerformed
        btn_simpan2.setEnabled(true);
        kode_pelanggan.requestFocus();
        btn_new2.setEnabled(true);
        btn_update2.setEnabled(false);
        btn_delete2.setEnabled(false);
        kode_pelanggan.setText("");
        tarif.setText("");
        alamat.setText("");
        no_hp.setText("");
        jenis_tarif.setSelectedItem("Laki-Laki");
        agama.setSelectedItem("Islam");
        Calendar today = Calendar.getInstance();
        tanggal_lahir.setCalendar(today);
        kode_pelanggan.setEnabled(true);
        jenis_tarif.setSelectedItem("-- Pilih Jenis Tarif --");
        tarif.setText("");
        keterangan.setText("");
    }//GEN-LAST:event_btn_new2ActionPerformed

    private byte CariKode(){
        byte urutan = -1;
        for(byte i=0;  i < this.support.getList().size(); i++){
            if(this.support.getList().get(i).getKodePelanggan().equals(kode_pelanggan.getText())){
                    urutan = i;
                    break;
            }
        }
        return urutan;
    }
    
    private void btn_simpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan2ActionPerformed
        Pelanggan e = new Pelanggan(
                kode_pelanggan.getText(), 
                nama_lengkap.getText(), 
                jenis_kelamin.getSelectedItem().toString(), 
                String.valueOf(tanggal_lahir.getDayChooser().getDay()) + "-" + String.valueOf(tanggal_lahir.getMonthChooser().getMonth() + 1) + "-" + String.valueOf(tanggal_lahir.getYearChooser().getYear()),
                alamat.getText(),
                agama.getSelectedItem().toString(),
                no_hp.getText(),
                jenis_tarif.getSelectedItem().toString(),
                Double.parseDouble(tarif.getText()),
                keterangan.getText());
        support.insertData(e);
        clearForm();
        tampilData();
        JOptionPane.showMessageDialog(null, "Data Berhasil Di Tambahkan!");
    }//GEN-LAST:event_btn_simpan2ActionPerformed

    private void btn_update2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update2ActionPerformed
        byte urutan = this.CariKode();
         Pelanggan e = new Pelanggan(
                kode_pelanggan.getText(), 
                nama_lengkap.getText(), 
                jenis_kelamin.getSelectedItem().toString(), 
                String.valueOf(tanggal_lahir.getDayChooser().getDay()) + "-" + String.valueOf(tanggal_lahir.getMonthChooser().getMonth() + 1) + "-" + String.valueOf(tanggal_lahir.getYearChooser().getYear()),
                alamat.getText(),
                agama.getSelectedItem().toString(),
                no_hp.getText(),
                jenis_tarif.getSelectedItem().toString(),
                Double.parseDouble(tarif.getText()),
                keterangan.getText());
        this.support.updateData(urutan, e);
        clearForm();
        tampilData();
        JOptionPane.showMessageDialog(null, "Data Berhasil Di Update!");
    }//GEN-LAST:event_btn_update2ActionPerformed

    private void btn_delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete2ActionPerformed
        int opsi = JOptionPane.showConfirmDialog(null, "Anda Yakin Ingin Menghapus Data Ini ?",
            "Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (opsi == JOptionPane.YES_OPTION){
            this.support.deleteData(this.CariKode());
            clearForm();
            tampilData();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus!");
        }

    }//GEN-LAST:event_btn_delete2ActionPerformed

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
        kode_pelanggan.setText(support.getItemInTable(1));
        nama_lengkap.setText(support.getItemInTable(2));
        jenis_kelamin.setSelectedItem(support.getItemInTable(3));
        tanggal_lahir.getDayChooser().setDay(Integer.parseInt(support.getDay(support.getItemInTable(4))));
        tanggal_lahir.getMonthChooser().setMonth(Integer.parseInt(support.getMonth(support.getItemInTable(4))) - 1);
        tanggal_lahir.getYearChooser().setYear(Integer.parseInt(support.getYear(support.getItemInTable(4))));
        alamat.setText(support.getItemInTable(5));
        agama.setSelectedItem(support.getItemInTable(6));
        no_hp.setText(support.getItemInTable(7));
        jenis_tarif.setSelectedItem(support.getItemInTable(8));
        tarif.setText(support.getItemInTable(9));
        keterangan.setText(support.getItemInTable(10));
        btn_new2.setEnabled(true);
        btn_simpan2.setEnabled(false);
        btn_update2.setEnabled(true);
        btn_delete2.setEnabled(true);
        kode_pelanggan.setEnabled(false);
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void cari_dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_dataKeyPressed
        support.cariData(cari_data.getText());
    }//GEN-LAST:event_cari_dataKeyPressed

    private byte CariGolongan(String tmp){
        byte urutan = -1;
        for(byte i=0;  i < this.support.getList().size(); i++){
            if(this.support.getList().get(i).getGolongan().equals(tmp)){
                    urutan = i;
                    break;
            }
        }
        return urutan;
    }
    
    private void jenis_tarifPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jenis_tarifPopupMenuWillBecomeInvisible
        String tmp = (String)jenis_tarif.getSelectedItem();
        tarif.setText("");
        keterangan.setText("");
        for(int i= 0; i<JenisTarif.jenis_tarif.size(); i++){
            if(JenisTarif.jenis_tarif.get(i).getGolongan().equals(tmp)){
                tarif.setText(String.valueOf(JenisTarif.jenis_tarif.get(i).getTarif()));
                keterangan.setText(JenisTarif.jenis_tarif.get(i).getKeterangan());
            }
        }
    }//GEN-LAST:event_jenis_tarifPopupMenuWillBecomeInvisible

    private void clearForm(){
        kode_pelanggan.setText("");
        nama_lengkap.setText("");
        alamat.setText("");
        no_hp.setText("");
        jenis_kelamin.setSelectedItem("Laki-Laki");
        agama.setSelectedItem("Islam");
        Calendar today = Calendar.getInstance();
        tanggal_lahir.setCalendar(today);
        jenis_tarif.setSelectedItem("-- Pilih Jenis Tarif --");
        tarif.setText("");
        keterangan.setText("");
        btn_new2.setEnabled(true);
        btn_simpan2.setEnabled(false);
        btn_update2.setEnabled(false);
        btn_delete2.setEnabled(false);
        kode_pelanggan.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agama;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btn_delete2;
    private javax.swing.JButton btn_new2;
    private javax.swing.JButton btn_simpan2;
    private javax.swing.JButton btn_update2;
    private javax.swing.JTextField cari_data;
    private org.jdatepicker.impl.DateComponentFormatter dateComponentFormatter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JComboBox<String> jenis_tarif;
    private javax.swing.JTextField keterangan;
    private javax.swing.JTextField kode_pelanggan;
    private javax.swing.JTextField nama_lengkap;
    private javax.swing.JTextField no_hp;
    private javax.swing.JTable tablePelanggan;
    private com.toedter.calendar.JCalendar tanggal_lahir;
    private javax.swing.JTextField tarif;
    // End of variables declaration//GEN-END:variables
}
