/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.akhir;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author alhamdi
 */
public class Menu extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Menu
     */
    
    private SimpleDateFormat format;
    private Timer timer;
    private Date date;

    
    
    public JMenuItem getMenuDataPelanggan() {
        return MenuDataPelanggan;
    }

    public JMenuItem getMenuDataUser() {
        return MenuDataUser;
    }

    public JMenuItem getMenuJenisTarif() {
        return MenuJenisTarif;
    }

    public JMenu getMenuMaster() {
        return MenuMaster;
    }
    
    public JLabel getRole() {
        return role;
    }

    public JLabel getNama() {
        return nama;
    }
    
    public Menu() {
        initComponents();
        timer = new Timer(1000, this);
        format = new SimpleDateFormat("dd MMMM yyyy, HH:m:ss");
        date = new Date();
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        username2 = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuMaster = new javax.swing.JMenu();
        MenuDataUser = new javax.swing.JMenuItem();
        MenuJenisTarif = new javax.swing.JMenuItem();
        MenuDataPelanggan = new javax.swing.JMenuItem();
        MenuPembayaran = new javax.swing.JMenu();
        MenuPembayaranListrik = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();
        MenuLaporanBulanan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN MENU");

        username.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("LISTRIK PLN");

        username1.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        username1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username1.setText("APLIKASI");

        username2.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        username2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username2.setText("PEMBAYARAN");

        tgl.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tgl.setText("-");

        nama.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nama.setText("-");

        role.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        role.setText("-");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        MenuMaster.setText("Data Master");

        MenuDataUser.setText("Data User");
        MenuDataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataUserActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuDataUser);

        MenuJenisTarif.setText("Data Jenis Tarif");
        MenuJenisTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuJenisTarifActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuJenisTarif);

        MenuDataPelanggan.setText("Pendaftaran Pelanggan");
        MenuDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDataPelangganActionPerformed(evt);
            }
        });
        MenuMaster.add(MenuDataPelanggan);

        jMenuBar1.add(MenuMaster);

        MenuPembayaran.setText("Pembayaran");

        MenuPembayaranListrik.setText("Pembayaran Listrik");
        MenuPembayaranListrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPembayaranListrikActionPerformed(evt);
            }
        });
        MenuPembayaran.add(MenuPembayaranListrik);

        jMenuBar1.add(MenuPembayaran);

        MenuLaporan.setText("Laporan");

        MenuLaporanBulanan.setText("Laporan Bulanan");
        MenuLaporanBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLaporanBulananActionPerformed(evt);
            }
        });
        MenuLaporan.add(MenuLaporanBulanan);

        jMenuBar1.add(MenuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(role)
                            .addComponent(tgl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(username2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(username)))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(jButton1))
                .addGap(6, 6, 6)
                .addComponent(role)
                .addGap(126, 126, 126)
                .addComponent(username1)
                .addGap(18, 18, 18)
                .addComponent(username2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(tgl)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataUserActionPerformed
        DataUser du = new DataUser();
        du.setVisible(true);
    }//GEN-LAST:event_MenuDataUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MenuDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDataPelangganActionPerformed
        DataPelanggan l = new DataPelanggan();
        l.setVisible(true);
    }//GEN-LAST:event_MenuDataPelangganActionPerformed

    private void MenuJenisTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuJenisTarifActionPerformed
        DataJenisTarif l = new DataJenisTarif();
        l.setVisible(true);
    }//GEN-LAST:event_MenuJenisTarifActionPerformed

    private void MenuPembayaranListrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPembayaranListrikActionPerformed
        DataPembayaran l = new DataPembayaran();
        l.getNama_petugas().setText(nama.getText().split(",")[1].trim());
        l.setVisible(true);
    }//GEN-LAST:event_MenuPembayaranListrikActionPerformed

    private void MenuLaporanBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLaporanBulananActionPerformed
        Laporan l = new Laporan();
        l.setVisible(true);
    }//GEN-LAST:event_MenuLaporanBulananActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuDataPelanggan;
    private javax.swing.JMenuItem MenuDataUser;
    private javax.swing.JMenuItem MenuJenisTarif;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuItem MenuLaporanBulanan;
    private javax.swing.JMenu MenuMaster;
    private javax.swing.JMenu MenuPembayaran;
    private javax.swing.JMenuItem MenuPembayaranListrik;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel role;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel username2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        date.setTime(System.currentTimeMillis());
        tgl.setText(format.format(date));
    }
}
