/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyek.akhir;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JLabel;
import proyek.akhir.model.Pembayaran;

/**
 *
 * @author alhamdi
 */
public class Print extends javax.swing.JFrame {

    public JLabel getNo_pembayaran() {
        return no_pembayaran;
    }

    public void setNo_pembayaran(JLabel no_pembayaran) {
        this.no_pembayaran = no_pembayaran;
    }

    public JLabel getAlamat() {
        return alamat;
    }

    public void setAlamat(JLabel alamat) {
        this.alamat = alamat;
    }

    public JLabel getDenda() {
        return denda;
    }

    public void setDenda(JLabel denda) {
        this.denda = denda;
    }

    public JLabel getGolongan() {
        return golongan;
    }

    public void setGolongan(JLabel golongan) {
        this.golongan = golongan;
    }

    public JLabel getJenis_kelamin() {
        return jenis_kelamin;
    }

    public void setJenis_kelamin(JLabel jenis_kelamin) {
        this.jenis_kelamin = jenis_kelamin;
    }

    public JLabel getKeterangan() {
        return keterangan;
    }

    public void setKeterangan(JLabel keterangan) {
        this.keterangan = keterangan;
    }

    public JLabel getKonsumsi_daya() {
        return konsumsi_daya;
    }

    public void setKonsumsi_daya(JLabel konsumsi_daya) {
        this.konsumsi_daya = konsumsi_daya;
    }

    public JLabel getNama() {
        return nama;
    }

    public void setNama(JLabel nama) {
        this.nama = nama;
    }

    public JLabel getTanggal_pembayaran() {
        return tanggal_pembayaran;
    }

    public void setTanggal_pembayaran(JLabel tanggal_pembayaran) {
        this.tanggal_pembayaran = tanggal_pembayaran;
    }

    public JLabel getTarif() {
        return tarif;
    }

    public void setTarif(JLabel tarif) {
        this.tarif = tarif;
    }

    public JLabel getTot_konsumsi_daya() {
        return tot_konsumsi_daya;
    }

    public void setTot_konsumsi_daya(JLabel tot_konsumsi_daya) {
        this.tot_konsumsi_daya = tot_konsumsi_daya;
    }

    public JLabel getTotal_bayar() {
        return total_bayar;
    }

    public void setTotal_bayar(JLabel total_bayar) {
        this.total_bayar = total_bayar;
    }

    public JLabel getTotal_konsumsi_daya() {
        return total_konsumsi_daya;
    }

    public void setTotal_konsumsi_daya(JLabel total_konsumsi_daya) {
        this.total_konsumsi_daya = total_konsumsi_daya;
    }
    
    
    
    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        no_pembayaran = new javax.swing.JLabel();
        tanggal_pembayaran = new javax.swing.JLabel();
        konsumsi_daya = new javax.swing.JLabel();
        total_konsumsi_daya = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        golongan = new javax.swing.JLabel();
        tarif = new javax.swing.JLabel();
        keterangan = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tot_konsumsi_daya = new javax.swing.JLabel();
        denda = new javax.swing.JLabel();
        total_bayar = new javax.swing.JLabel();

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STRUK PEMBAYARAN");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No Pembayaran");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tanggal Pembayaran");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Konsumsi Daya (W)");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Konsumsi Daya (kWh)");

        no_pembayaran.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        no_pembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_pembayaran.setText("-");

        tanggal_pembayaran.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tanggal_pembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tanggal_pembayaran.setText("-");

        konsumsi_daya.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        konsumsi_daya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        konsumsi_daya.setText("-");

        total_konsumsi_daya.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        total_konsumsi_daya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_konsumsi_daya.setText("-");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DATA PELANGGAN");

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nama");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Jenis Kelamin");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Alamat");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DATA TARIF GOLONGAN");

        nama.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("-");

        jenis_kelamin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jenis_kelamin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jenis_kelamin.setText("-");

        alamat.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        alamat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamat.setText("-");

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Golongan");

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tarif");

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Keterangan");

        golongan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        golongan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        golongan.setText("-");

        tarif.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tarif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tarif.setText("-");

        keterangan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        keterangan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keterangan.setText("-");

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Tarif Konsumsi Daya");

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Denda");

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Total Bayar");

        tot_konsumsi_daya.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tot_konsumsi_daya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tot_konsumsi_daya.setText("-");

        denda.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        denda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        denda.setText("-");

        total_bayar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        total_bayar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_bayar.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(181, 181, 181)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(25, 25, 25))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(57, 57, 57)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(no_pembayaran)
                                                .addComponent(tanggal_pembayaran)
                                                .addComponent(konsumsi_daya)
                                                .addComponent(total_konsumsi_daya)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(58, 58, 58)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jenis_kelamin)
                                                .addComponent(nama)
                                                .addComponent(alamat)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20))
                                    .addGap(162, 162, 162)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tarif)
                                        .addComponent(keterangan)
                                        .addComponent(tot_konsumsi_daya)
                                        .addComponent(denda)
                                        .addComponent(total_bayar)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(175, 175, 175)
                                    .addComponent(golongan))
                                .addComponent(jLabel26)
                                .addComponent(jLabel25))))
                    .addContainerGap(143, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 460, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(no_pembayaran))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(tanggal_pembayaran))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(konsumsi_daya))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(total_konsumsi_daya))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel10)
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(nama))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jenis_kelamin))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(alamat))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(golongan))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tarif))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(keterangan))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(tot_konsumsi_daya))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(denda))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(total_bayar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        
        job.setJobName("Struk Pembayaran");
        job.setPrintable(new Printable(){
            @Override
            public int print(Graphics grphcs, PageFormat pf, int i) throws PrinterException {
               if(i>0){
                   return Printable.NO_SUCH_PAGE;
               }
               
               Graphics2D g2 = (Graphics2D)grphcs;
               g2.translate(pf.getImageableX(), pf.getImageableY());
               g2.scale(0.24, 0.24);
               
               jPanel1.paint(g2);
               return Printable.PAGE_EXISTS;
            }
            
        });
        
        Boolean ok = job.printDialog();
        if(ok){
            try{
                job.print();
            }catch(PrinterException ex){
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel denda;
    private javax.swing.JLabel golongan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenis_kelamin;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel konsumsi_daya;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel no_pembayaran;
    private javax.swing.JLabel tanggal_pembayaran;
    private javax.swing.JLabel tarif;
    private javax.swing.JLabel tot_konsumsi_daya;
    private javax.swing.JLabel total_bayar;
    private javax.swing.JLabel total_konsumsi_daya;
    // End of variables declaration//GEN-END:variables
}
